### ISSUE TITLE
Twitch freezes when you put up a live stream

### ISSUE THREAD

**Issue by Dan06567** [rtd1250/android_device_samsung_a70q#3]
https://user-images.githubusercontent.com/89529371/201487366-2468a097-1871-4ccb-9b54-c1bab4662f16.mp4

Twitch freezes when you put up a live stream and it say "not responding"

**Comment by Dan06567** [comment]
LineageOS 20

**Comment by rtd1250** [comment]
Yeah this is a known issue, and Twitch's app is really crappy too. For the time being I suggest using other Twitch client, like:
https://github.com/tommyxchow/frosty
or
https://github.com/twireapp/Twire

**Comment by Dan06567** [comment]
Thank you, anyway i like your Custom Rom. It feels like using a new phone. The One UI sucked

**Comment by rtd1250** [comment]
Fixed as of https://github.com/rtd1250/android_device_samsung_a70q/commit/543979c990a74bdfe152850833a89a9b0c1c0386
