### ISSUE TITLE
Thank you for your respectable work

### ISSUE THREAD

**Issue by mary-ng5519** [rtd1250/android_device_samsung_a70q#7]
Dear, would you please have a tutorial about detail steps of building process
We love your work and would like to contribute system-based app development efforts

**Comment by rtd1250** [comment]
Such an insightful issue calls for an insightful response:

Thank you so much for your kind words and enthusiasm about our work! We're thrilled to hear that you appreciate what we've been doing. It's always heartwarming to know that our efforts are making a positive impact. Your interest in contributing to our system-based app development efforts is truly exciting. We believe that collaboration is at the heart of open-source development, and we welcome contributions from passionate individuals like you. Your expertise and contributions can help us push the boundaries of what's possible and make our projects even better. Please feel free to reach out, and we can discuss how you can get involved. Once again, thank you for your support, and we look forward to working together to create exceptional system-based applications!

Building LineageOS for an unofficially supported device involves several steps, and it can be a complex process. Here's a concise overview:

1. Set Up a Build Environment:
Install required development tools like Git, Python, and Java.
Set up a Linux environment, preferably Ubuntu.
Install necessary build dependencies using your device's manufacturer guidelines or LineageOS documentation.
2. Get the Source Code:
Initialize a local repository using repo tool (from Google).
Sync the LineageOS source code using repo sync.
3. Device Tree and Kernel Sources:
Find or create a device tree for your device in the "device" directory.
Ensure you have the correct kernel sources compatible with LineageOS.
4. Apply Patches (if necessary):
If your device requires specific patches, apply them to the LineageOS source code.
5. Build LineageOS:
Configure the build for your device using lunch command.
Start the build process using make or brunch command.
The compilation will take time, depending on your hardware.
6. Generate Recovery and Boot Images:
After a successful build, you'll find the flashable recovery and boot images in the "out/target/product/your_device" directory.
7. Flash the ROM:
Unlock your device's bootloader (if necessary).
Flash the recovery image using fastboot.
Use the custom recovery to install the LineageOS zip file.
8. GApps and Add-ons (Optional):
If desired, flash Google Apps (GApps) and other add-ons.
9. Test and Debug:
Boot into LineageOS and check for any issues or bugs.
Use developer tools to diagnose and debug problems.
10. Contribute to LineageOS (Optional):
If you've successfully built LineageOS for your device, consider sharing your work with the LineageOS community by submitting your changes for review.

Please note that this is a high-level overview, and the specifics can vary depending on your device and its peculiarities. Building LineageOS for an unofficially supported device requires technical knowledge, patience, and a willingness to troubleshoot issues that may arise during the process. Be sure to consult LineageOS forums and documentation for device-specific guidance and updates.
